"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {lessons} from "../course-data";

type Row={id:string;name:string;className:string;currentLesson:number;currentStage:string;completedCount:number;lastActiveAt:string;hasPin:boolean};

export default function Professor(){
 const [rows,setRows]=useState<Row[]>([]),[password,setPassword]=useState(""),[authorized,setAuthorized]=useState(false),[error,setError]=useState(""),[filter,setFilter]=useState("Todas");
 const [studentName,setStudentName]=useState(""),[studentClass,setStudentClass]=useState(""),[generatedPin,setGeneratedPin]=useState<{name:string;pin:string}|null>(null),[pinError,setPinError]=useState(""),[managingPin,setManagingPin]=useState(false);
 const [currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[passwordMessage,setPasswordMessage]=useState(""),[passwordError,setPasswordError]=useState(""),[changing,setChanging]=useState(false);
 async function load(){const r=await fetch("/api/students");if(r.ok){setRows((await r.json()).students);setAuthorized(true)}}
 useEffect(()=>{load()},[]);
 async function login(e:FormEvent){e.preventDefault();setError("");const r=await fetch("/api/professor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});const data=await r.json();if(!r.ok){setError(data.error);return}setAuthorized(true);setPassword("");load()}
 async function createStudent(e:FormEvent){e.preventDefault();setPinError("");setManagingPin(true);const r=await fetch("/api/students/manage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:studentName,className:studentClass})});const data=await r.json();setManagingPin(false);if(!r.ok){setPinError(data.error);return}setGeneratedPin({name:data.student.name,pin:data.pin});setStudentName("");setStudentClass("");load()}
 async function resetPin(student:Row){if(!confirm(`Gerar um novo PIN para ${student.name}? O PIN anterior deixará de funcionar.`))return;setPinError("");const r=await fetch("/api/students/manage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({studentId:student.id})});const data=await r.json();if(!r.ok){setPinError(data.error);return}setGeneratedPin({name:data.student.name,pin:data.pin});load()}
 async function changePassword(e:FormEvent){e.preventDefault();setPasswordError("");setPasswordMessage("");if(newPassword!==confirmPassword){setPasswordError("A confirmação não corresponde à nova senha.");return}setChanging(true);const r=await fetch("/api/professor",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({currentPassword,newPassword})});const data=await r.json();setChanging(false);if(!r.ok){setPasswordError(data.error);return}setCurrentPassword("");setNewPassword("");setConfirmPassword("");setPasswordMessage("Senha alterada com sucesso. Sua sessão foi renovada.")}
 const classes=useMemo(()=>["Todas",...Array.from(new Set(rows.map(x=>x.className)))],[rows]),shown=filter==="Todas"?rows:rows.filter(x=>x.className===filter);
 if(!authorized)return <main className="teacher-login"><form onSubmit={login}><Link className="brand" href="/"><span className="brandmark">&gt;_</span><span>python<span>dozero</span></span></Link><span className="section-kicker">ÁREA RESTRITA</span><h1>Painel do professor</h1><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoFocus/></label>{error&&<p className="form-error">{error}</p>}<button className="primary">Entrar</button><Link href="/">← Voltar ao curso</Link></form></main>;
 return <main className="teacher-panel">
  <header><div><span className="section-kicker">PAINEL DO PROFESSOR</span><h1>Acompanhamento das turmas</h1><p>{rows.length} aluno{rows.length===1?"":"s"} identificado{rows.length===1?"":"s"}</p></div><div><select value={filter} onChange={e=>setFilter(e.target.value)}>{classes.map(x=><option key={x}>{x}</option>)}</select><button onClick={load}>Atualizar</button></div></header>
  <section className="student-manager"><div><span className="section-kicker">ACESSO DOS ALUNOS</span><h2>Cadastrar aluno e gerar PIN</h2><p>O PIN aparece somente agora. Entregue-o diretamente ao aluno.</p></div><form onSubmit={createStudent}><label>Nome completo<input value={studentName} onChange={e=>setStudentName(e.target.value)} required minLength={2} placeholder="Nome do aluno"/></label><label>Turma<select value={studentClass} onChange={e=>setStudentClass(e.target.value)} required><option value="">Selecione</option><option>1º Ano Técnico</option><option>2º Ano Técnico</option><option>3º Ano Técnico</option></select></label>{pinError&&<p className="form-error" role="alert">{pinError}</p>}<button className="primary" disabled={managingPin}>{managingPin?"Gerando...":"Cadastrar e gerar PIN"}</button></form>{generatedPin&&<div className="generated-pin" role="status"><span>PIN de <b>{generatedPin.name}</b></span><strong>{generatedPin.pin}</strong><button onClick={()=>navigator.clipboard.writeText(generatedPin.pin)}>Copiar PIN</button><button onClick={()=>setGeneratedPin(null)} aria-label="Fechar">×</button></div>}</section>
  <section className="teacher-table"><table><thead><tr><th>Aluno</th><th>Turma</th><th>Aula atual</th><th>Etapa</th><th>Progresso</th><th>Última atividade</th><th>PIN</th><th>Ação</th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td><span className="class-chip">{x.className}</span></td><td>{String(x.currentLesson).padStart(2,"0")} · {lessons[x.currentLesson-1]?.title||"Curso concluído"}</td><td>{x.currentStage}</td><td><div className="mini-progress"><i style={{width:`${x.completedCount/20*100}%`}}/></div><small>{x.completedCount}/20</small></td><td>{new Date(x.lastActiveAt).toLocaleString("pt-BR")}</td><td><span className={x.hasPin?"pin-ready":"pin-missing"}>{x.hasPin?"Configurado":"Pendente"}</span></td><td><button className="reset-pin" onClick={()=>resetPin(x)}>{x.hasPin?"Redefinir PIN":"Gerar PIN"}</button></td></tr>)}</tbody></table>{shown.length===0&&<p className="empty-state">Nenhum aluno nesta turma ainda.</p>}</section>
  <section className="password-panel"><div><span className="section-kicker">SEGURANÇA</span><h2>Alterar senha do professor</h2><p>Use uma senha exclusiva com pelo menos 10 caracteres.</p></div><form onSubmit={changePassword}><label>Senha atual<input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} required autoComplete="current-password"/></label><label>Nova senha<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} required minLength={10} autoComplete="new-password"/></label><label>Confirmar nova senha<input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required minLength={10} autoComplete="new-password"/></label><small>A nova senha deve ter maiúscula, minúscula, número e símbolo.</small>{passwordError&&<p className="form-error" role="alert">{passwordError}</p>}{passwordMessage&&<p className="form-success" role="status">{passwordMessage}</p>}<button className="primary" disabled={changing}>{changing?"Alterando...":"Alterar senha"}</button></form></section>
  <Link className="teacher-back" href="/">← Voltar ao curso</Link>
 </main>
}
