"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {lessons} from "../course-data";

type Post={id:string;className:string;kind:string;title:string;content:string;dueDate:string|null;createdAt:string;deliveredCount?:number};
type Row={id:string;name:string;className:string;currentLesson:number;currentStage:string;completedCount:number;lastActiveAt:string;hasPin:boolean};

export default function Professor(){
 const [rows,setRows]=useState<Row[]>([]),[password,setPassword]=useState(""),[authorized,setAuthorized]=useState(false),[error,setError]=useState(""),[filter,setFilter]=useState("Todas"),[difficulty,setDifficulty]=useState("Todos"),[search,setSearch]=useState(""),[posts,setPosts]=useState<Post[]>([]);
 const [studentName,setStudentName]=useState(""),[studentClass,setStudentClass]=useState(""),[generatedPin,setGeneratedPin]=useState<{name:string;pin:string}|null>(null),[pinError,setPinError]=useState(""),[managingPin,setManagingPin]=useState(false);
 const [currentPassword,setCurrentPassword]=useState(""),[newPassword,setNewPassword]=useState(""),[confirmPassword,setConfirmPassword]=useState(""),[passwordMessage,setPasswordMessage]=useState(""),[passwordError,setPasswordError]=useState(""),[changing,setChanging]=useState(false),[postClass,setPostClass]=useState("Todas"),[postKind,setPostKind]=useState("Recado"),[postTitle,setPostTitle]=useState(""),[postContent,setPostContent]=useState(""),[postDue,setPostDue]=useState(""),[postError,setPostError]=useState("");
 async function load(){const r=await fetch("/api/students");if(r.ok){setRows((await r.json()).students);setAuthorized(true);fetch("/api/classroom").then(r=>r.ok?r.json():{posts:[]}).then(data=>setPosts(data.posts||[]))}}
 useEffect(()=>{load()},[]);
 async function login(e:FormEvent){e.preventDefault();setError("");const r=await fetch("/api/professor",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});const data=await r.json();if(!r.ok){setError(data.error);return}setAuthorized(true);setPassword("");load()}
 async function createStudent(e:FormEvent){e.preventDefault();setPinError("");setManagingPin(true);const r=await fetch("/api/students/manage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:studentName,className:studentClass})});const data=await r.json();setManagingPin(false);if(!r.ok){setPinError(data.error);return}setGeneratedPin({name:data.student.name,pin:data.pin});setStudentName("");setStudentClass("");load()}
 async function resetPin(student:Row){if(!confirm(`Gerar um novo PIN para ${student.name}? O PIN anterior deixará de funcionar.`))return;setPinError("");const r=await fetch("/api/students/manage",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({studentId:student.id})});const data=await r.json();if(!r.ok){setPinError(data.error);return}setGeneratedPin({name:data.student.name,pin:data.pin});load()}
 async function changePassword(e:FormEvent){e.preventDefault();setPasswordError("");setPasswordMessage("");if(newPassword!==confirmPassword){setPasswordError("A confirmação não corresponde à nova senha.");return}setChanging(true);const r=await fetch("/api/professor",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({currentPassword,newPassword})});const data=await r.json();setChanging(false);if(!r.ok){setPasswordError(data.error);return}setCurrentPassword("");setNewPassword("");setConfirmPassword("");setPasswordMessage("Senha alterada com sucesso. Sua sessão foi renovada.")}
 async function publishPost(e:FormEvent){e.preventDefault();setPostError("");const r=await fetch("/api/classroom",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({className:postClass,kind:postKind,title:postTitle,content:postContent,dueDate:postDue})});const data=await r.json();if(!r.ok){setPostError(data.error);return}setPostTitle("");setPostContent("");setPostDue("");load()}
 async function removePost(id:string){if(!confirm("Excluir esta publicação?"))return;await fetch(`/api/classroom?id=${id}`,{method:"DELETE"});load()}
 const classes=useMemo(()=>["Todas",...Array.from(new Set(rows.map(x=>x.className)))],[rows]);
 const shown=rows.filter(x=>filter==="Todas"||x.className===filter).filter(x=>x.name.toLowerCase().includes(search.toLowerCase())).filter(x=>difficulty==="Todos"||(difficulty==="Atenção"?x.completedCount<5&&Date.now()-new Date(x.lastActiveAt).getTime()>7*86400000:difficulty==="Em andamento"?x.completedCount>0&&x.completedCount<20:x.completedCount===20));
 if(!authorized)return <main className="teacher-login"><form onSubmit={login}><Link className="brand" href="/"><span className="brandmark">&gt;_</span><span>python<span>dozero</span></span></Link><span className="section-kicker">ÁREA RESTRITA</span><h1>Painel do professor</h1><label>Senha<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required autoFocus/></label>{error&&<p className="form-error">{error}</p>}<button className="primary">Entrar</button><Link href="/">← Voltar ao curso</Link></form></main>;
 return <main className="teacher-panel">
  <header><div><span className="section-kicker">PAINEL DO PROFESSOR</span><h1>Acompanhamento das turmas</h1><p>{rows.length} aluno{rows.length===1?"":"s"} identificado{rows.length===1?"":"s"}</p><Link className="review-link" href="/professor/correcoes">📝 Corrigir atividades</Link></div><div><input className="teacher-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar aluno"/><select value={filter} onChange={e=>setFilter(e.target.value)}>{classes.map(x=><option key={x}>{x}</option>)}</select><select value={difficulty} onChange={e=>setDifficulty(e.target.value)}><option>Todos</option><option>Atenção</option><option>Em andamento</option><option>Concluído</option></select><button onClick={load}>Atualizar</button></div></header>
  <section className="student-manager"><div><span className="section-kicker">ACESSO DOS ALUNOS</span><h2>Cadastrar aluno e gerar PIN</h2><p>O PIN aparece somente agora. Entregue-o diretamente ao aluno.</p></div><form onSubmit={createStudent}><label>Nome completo<input value={studentName} onChange={e=>setStudentName(e.target.value)} required minLength={2} placeholder="Nome do aluno"/></label><label>Turma<select value={studentClass} onChange={e=>setStudentClass(e.target.value)} required><option value="">Selecione</option><option>1º Ano Técnico</option><option>2º Ano Técnico</option><option>3º Ano Técnico</option></select></label>{pinError&&<p className="form-error" role="alert">{pinError}</p>}<button className="primary" disabled={managingPin}>{managingPin?"Gerando...":"Cadastrar e gerar PIN"}</button></form>{generatedPin&&<div className="generated-pin" role="status"><span>PIN de <b>{generatedPin.name}</b></span><strong>{generatedPin.pin}</strong><button onClick={()=>navigator.clipboard.writeText(generatedPin.pin)}>Copiar PIN</button><button onClick={()=>setGeneratedPin(null)} aria-label="Fechar">×</button></div>}</section>
  <section className="classroom-manager"><div><span className="section-kicker">MURAL DAS TURMAS</span><h2>Publicar recado ou atividade</h2><p>Escolha uma turma ou envie para todas.</p></div><form onSubmit={publishPost}><label>Turma<select value={postClass} onChange={e=>setPostClass(e.target.value)}><option>Todas</option><option>1º Ano Técnico</option><option>2º Ano Técnico</option><option>3º Ano Técnico</option></select></label><label>Tipo<select value={postKind} onChange={e=>setPostKind(e.target.value)}><option>Recado</option><option>Atividade</option></select></label><label className="wide">Título<input value={postTitle} onChange={e=>setPostTitle(e.target.value)} required/></label><label className="wide">Descrição<textarea value={postContent} onChange={e=>setPostContent(e.target.value)} required/></label>{postKind==="Atividade"&&<label>Data de entrega<input type="date" value={postDue} onChange={e=>setPostDue(e.target.value)}/></label>}{postError&&<p className="form-error">{postError}</p>}<button className="primary">Publicar no mural</button></form><div className="published-posts">{posts.slice(0,6).map(p=><article key={p.id}><span>{p.kind} · {p.className}</span><b>{p.title}{p.kind==="Atividade"&&<small>{p.deliveredCount||0} entrega(s)</small>}</b><button onClick={()=>removePost(p.id)}>Excluir</button></article>)}</div></section>
  <section className="filter-summary"><b>{shown.length} aluno(s) no filtro</b><span>“Atenção” identifica aluno com menos de 5 aulas e sem atividade há mais de 7 dias.</span></section>
  <section className="teacher-table"><table><thead><tr><th>Aluno</th><th>Turma</th><th>Aula atual</th><th>Etapa</th><th>Progresso</th><th>Última atividade</th><th>PIN</th><th>Ação</th></tr></thead><tbody>{shown.map(x=><tr key={x.id}><td><strong>{x.name}</strong></td><td><span className="class-chip">{x.className}</span></td><td>{String(x.currentLesson).padStart(2,"0")} · {lessons[x.currentLesson-1]?.title||"Curso concluído"}</td><td>{x.currentStage}</td><td><div className="mini-progress"><i style={{width:`${x.completedCount/20*100}%`}}/></div><small>{x.completedCount}/20</small></td><td>{new Date(x.lastActiveAt).toLocaleString("pt-BR")}</td><td><span className={x.hasPin?"pin-ready":"pin-missing"}>{x.hasPin?"Configurado":"Pendente"}</span></td><td><button className="reset-pin" onClick={()=>resetPin(x)}>{x.hasPin?"Redefinir PIN":"Gerar PIN"}</button></td></tr>)}</tbody></table>{shown.length===0&&<p className="empty-state">Nenhum aluno nesta turma ainda.</p>}</section>
  <section className="password-panel"><div><span className="section-kicker">SEGURANÇA</span><h2>Alterar senha do professor</h2><p>Use uma senha exclusiva com pelo menos 10 caracteres.</p></div><form onSubmit={changePassword}><label>Senha atual<input type="password" value={currentPassword} onChange={e=>setCurrentPassword(e.target.value)} required autoComplete="current-password"/></label><label>Nova senha<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} required minLength={10} autoComplete="new-password"/></label><label>Confirmar nova senha<input type="password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} required minLength={10} autoComplete="new-password"/></label><small>A nova senha deve ter maiúscula, minúscula, número e símbolo.</small>{passwordError&&<p className="form-error" role="alert">{passwordError}</p>}{passwordMessage&&<p className="form-success" role="status">{passwordMessage}</p>}<button className="primary" disabled={changing}>{changing?"Alterando...":"Alterar senha"}</button></form></section>
  <Link className="teacher-back" href="/">← Voltar ao curso</Link>
 </main>
}
