export type Lesson={slug:string;title:string;topic:string;summary:string;concept:string;code:string;activity:string;challenge:string};

export const lessons:Lesson[]=[
 {slug:"programacao-python",title:"Conhecendo a Programação e o Python",topic:"Fundamentos",summary:"Entenda como programas transformam entradas em resultados.",concept:"Programar é criar uma sequência lógica e finita de instruções. Antes de escrever código, compreenda o problema, identifique as entradas, organize o processamento e defina a saída esperada.",code:'print("Olá, mundo!")',activity:"Escreva um algoritmo com seis passos para preparar um sanduíche.",challenge:"Liste cinco funcionalidades essenciais de um sistema escolar."},
 {slug:"print",title:"Primeiro Programa: print()",topic:"Primeiros passos",summary:"Mostre textos e resultados na tela.",concept:"A função print() apresenta informações. Textos ficam entre aspas e cada instrução pode ocupar uma linha. Experimente mudar as mensagens e observe o resultado.",code:'print("====================")\nprint("   CURSO DE PYTHON")\nprint("====================")',activity:"Crie uma apresentação com nome, turma e objetivo de aprendizagem.",challenge:"Crie a tela inicial de um jogo com quatro opções."},
 {slug:"variaveis",title:"Variáveis e Tipos de Dados",topic:"Dados",summary:"Guarde textos, números e valores lógicos.",concept:"Variáveis são nomes que apontam para valores. Os tipos mais comuns no início são str, int, float e bool. Prefira nomes que expliquem o significado do dado.",code:'nome = "Mariana"\nidade = 16\naltura = 1.68\nmatriculado = True\nprint(nome, idade, altura, matriculado)',activity:"Crie variáveis para nome, idade, cidade, curso, nota e matrícula.",challenge:"Use type() para investigar o tipo de cada variável."},
 {slug:"input",title:"Entrada de Dados com input()",topic:"Interação",summary:"Receba informações digitadas pelo usuário.",concept:"input() sempre retorna texto. Para fazer cálculos, converta a entrada usando int() para números inteiros ou float() para números decimais.",code:'nome = input("Nome: ")\nidade = int(input("Idade: "))\nprint("Olá,", nome, "- idade:", idade)',activity:"Crie um cadastro com nome, cidade e curso.",challenge:"Crie um cadastro de jogador com nickname, idade e jogo favorito."},
 {slug:"operadores",title:"Operadores Matemáticos",topic:"Cálculos",summary:"Realize contas e construa cálculos úteis.",concept:"Python oferece adição, subtração, multiplicação, divisão, divisão inteira, resto e potência. Use parênteses para deixar a ordem do cálculo explícita.",code:'nota1 = float(input("Nota 1: "))\nnota2 = float(input("Nota 2: "))\nmedia = (nota1 + nota2) / 2\nprint("Média:", media)',activity:"Calcule o total de uma compra com três produtos.",challenge:"Registre três notas e calcule a média do estudante."},
 {slug:"if",title:"Tomada de Decisão com if",topic:"Decisões",summary:"Execute um bloco somente quando uma condição for verdadeira.",concept:"if significa “se”. O bloco indentado abaixo dele só é executado quando a condição resulta em verdadeiro. Em Python, a indentação faz parte da sintaxe.",code:'idade = int(input("Idade: "))\nif idade >= 18:\n    print("Maior de idade")',activity:"Peça a idade e informe quando for maior ou igual a 18.",challenge:"Exiba uma conquista quando o jogador alcançar mil pontos."},
 {slug:"elif-else",title:"if, elif e else",topic:"Decisões",summary:"Escolha entre vários caminhos possíveis.",concept:"O Python testa as condições de cima para baixo. if inicia a decisão, elif adiciona alternativas e else representa o caminho restante.",code:'media = float(input("Média: "))\nif media >= 6:\n    print("APROVADO")\nelif media >= 4:\n    print("RECUPERAÇÃO")\nelse:\n    print("REPROVADO")',activity:"Classifique a temperatura como quente, agradável ou fria.",challenge:"Crie um ranking com quatro níveis de pontuação."},
 {slug:"relacionais",title:"Operadores Relacionais",topic:"Comparações",summary:"Compare valores e produza verdadeiro ou falso.",concept:"Os operadores >, <, >=, <=, == e != comparam valores. Lembre-se: um sinal de igual atribui um valor; dois sinais comparam valores.",code:'senha = input("Senha: ")\nif senha == "python2026":\n    print("ACESSO AUTORIZADO")\nelse:\n    print("ACESSO NEGADO")',activity:"Teste cinco comparações e preveja o resultado antes de executar.",challenge:"Crie um login simples com uma senha definida no código."},
 {slug:"logicos",title:"Operadores Lógicos",topic:"Comparações",summary:"Combine condições com and, or e not.",concept:"and exige que todas as condições sejam verdadeiras; or aceita pelo menos uma; not inverte o resultado lógico. Combine-os com clareza.",code:'nivel = int(input("Nível: "))\nchave = input("Possui chave? ").strip().lower()\nif nivel >= 15 and chave == "sim":\n    print("DUNGEON LIBERADA")',activity:"Crie uma promoção para maiores de 60 anos ou estudantes.",challenge:"Defina duas formas diferentes de liberar uma dungeon."},
 {slug:"while",title:"Repetição com while",topic:"Repetições",summary:"Repita enquanto uma condição for verdadeira.",concept:"while é útil quando não sabemos quantas repetições serão necessárias. Atualize a variável da condição para impedir um laço infinito.",code:'contador = 1\nwhile contador <= 5:\n    print(contador)\n    contador += 1',activity:"Mostre de 1 a 10 e depois faça uma contagem regressiva.",challenge:"Crie um sistema de senha com no máximo três tentativas."},
 {slug:"for",title:"Repetição com for",topic:"Repetições",summary:"Percorra sequências de maneira simples.",concept:"for percorre itens de uma sequência. Junto com range(), é ideal quando conhecemos a quantidade de repetições.",code:'for numero in range(1, 6):\n    print(numero)',activity:"Mostre os números de 1 a 10 usando for.",challenge:"Crie a tabuada de um número informado pelo usuário."},
 {slug:"range",title:"range, Contadores e Acumuladores",topic:"Repetições",summary:"Controle intervalos, quantidades e somas.",concept:"range() recebe início, fim e passo. Contadores acompanham quantidades; acumuladores guardam somas progressivas.",code:'soma = 0\nfor i in range(5):\n    valor = float(input("Valor: "))\n    soma += valor\nprint("Total:", soma)',activity:"Solicite cinco números e mostre a soma.",challenge:"Registre a pontuação de cinco fases e mostre total e média."},
 {slug:"strings",title:"Trabalhando com Strings",topic:"Textos",summary:"Limpe, transforme e conte caracteres.",concept:"Strings são sequências de caracteres. Métodos como upper(), lower() e strip() transformam textos; len() informa seu tamanho.",code:'nome = input("Nome: ").strip()\nprint(nome.upper())\nprint(nome.lower())\nprint("Caracteres:", len(nome))',activity:"Mostre um nome completo em maiúsculas, minúsculas e conte caracteres.",challenge:"Valide um nickname com pelo menos cinco caracteres."},
 {slug:"listas",title:"Introdução às Listas",topic:"Coleções",summary:"Armazene vários valores em uma estrutura.",concept:"Listas organizam elementos em ordem. Cada elemento possui um índice que começa em zero e a lista pode ser percorrida com for.",code:'jogadores = ["Mariana", "Gabriel", "Hellen"]\nfor jogador in jogadores:\n    print(jogador)',activity:"Crie uma lista com cinco disciplinas e percorra com for.",challenge:"Apresente cinco personagens de jogos de forma numerada."},
 {slug:"manipulando-listas",title:"Manipulando Listas",topic:"Coleções",summary:"Adicione, remova, ordene e procure itens.",concept:"append() adiciona, remove() exclui, len() conta, in verifica a existência e sort() ordena. Essas operações permitem manter coleções dinâmicas.",code:'alunos = []\nfor i in range(5):\n    nome = input("Nome: ").strip()\n    alunos.append(nome)\nalunos.sort()\nprint(alunos)',activity:"Cadastre e ordene cinco alunos em uma lista.",challenge:"Crie um inventário e procure pela Chave Dourada."},
 {slug:"funcoes",title:"Criando Funções",topic:"Organização",summary:"Organize e reutilize blocos de código.",concept:"Funções são definidas com def e devem realizar uma tarefa clara. Elas evitam repetição e tornam o programa mais fácil de testar e manter.",code:'def cabecalho():\n    print("=" * 30)\n    print("SISTEMA ESCOLAR")\n    print("=" * 30)\n\ncabecalho()',activity:"Crie uma função mensagem() com o título do curso.",challenge:"Crie e chame as funções inicio(), menu() e fim()."},
 {slug:"parametros-retorno",title:"Parâmetros e Retorno",topic:"Organização",summary:"Envie dados para funções e receba resultados.",concept:"Parâmetros permitem que a função receba valores. return devolve um resultado, tornando a função útil em diferentes partes do programa.",code:'def calcular_media(n1, n2):\n    return (n1 + n2) / 2\n\nmedia = calcular_media(8, 6)\nprint(media)',activity:"Crie dobro(numero) e retorne o resultado.",challenge:"Crie classificar_jogador(pontos) e retorne o ranking."},
 {slug:"erros",title:"Tratamento de Erros",topic:"Qualidade",summary:"Evite que entradas inválidas encerrem o programa.",concept:"try/except permite responder a erros previstos. Prefira exceções específicas, como ValueError e ZeroDivisionError, em vez de capturar qualquer erro.",code:'try:\n    idade = int(input("Idade: "))\n    print(idade)\nexcept ValueError:\n    print("Digite apenas números inteiros.")',activity:"Solicite uma idade e trate uma entrada não numérica.",challenge:"Crie uma divisão que trate letras e divisão por zero."},
 {slug:"sistema-escolar",title:"Miniprojeto: Sistema Escolar",topic:"Projeto",summary:"Integre entrada, cálculos, decisões, listas e funções.",concept:"Projetos combinam conceitos pequenos em um fluxo completo. Planeje primeiro: cadastro, notas, média, situação, armazenamento e relatório.",code:'def calcular_media(n1, n2):\n    return (n1 + n2) / 2\n\ndef situacao(media):\n    if media >= 6: return "APROVADO"\n    if media >= 4: return "RECUPERAÇÃO"\n    return "REPROVADO"',activity:"Implemente cadastro de alunos com duas notas e situação.",challenge:"Adicione matrícula, turma, três notas e estatísticas."},
 {slug:"python-adventure",title:"Projeto Final: Python Adventure",topic:"Projeto final",summary:"Construa um pequeno RPG textual autoral.",concept:"Planeje personagem, classe, vida, nível, moedas, inventário e menu. Divida cada responsabilidade em funções e desenvolva o jogo em pequenas etapas.",code:'inventario = ["Poção", "Mapa"]\nvida = 100\nmoedas = 50\n\ndef mostrar_inventario():\n    for item in inventario:\n        print("-", item)',activity:"Planeje o menu e a ficha do herói antes de programar.",challenge:"Inclua loja, exploração, batalha, experiência e condição de vitória."},
];

export const storageKey="python-do-zero-progress-v2";
