"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {lessons} from "../../course-data";
import {logicLessons} from "../../logic-data";
type Review={studentId:string;name:string;className:string;lessonSlug:string;answer:string;reviewStatus:string;teacherFeedback:string;submittedAt:string|null;updatedAt:string};
export default function Correcoes(){
 const [items,setItems]=useState<Review[]>([]),[status,setStatus]=useState("entregue"),[className,setClassName]=useState("Todas"),[message,setMessage]=useState("");
 async function load(){const r=await fetch(`/api/reviews?className=${encodeURIComponent(className)}&status=${encodeURIComponent(status)}`);if(r.status===401){location.href="/professor";return}if(r.ok)setItems((await r.json()).reviews)}
 useEffect(()=>{load()},[status,className]);
 async function save(item:Review,newStatus:string,feedback:string){const r=await fetch("/api/reviews",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({studentId:item.studentId,lessonSlug:item.lessonSlug,status:newStatus,feedback})});if(r.ok){setMessage("Correção salva.");load()}}
 const classes=useMemo(()=>["Todas",...Array.from(new Set(items.map(x=>x.className)))],[items]);
 return <main className="review-page"><header><div><span className="section-kicker">PAINEL DO PROFESSOR</span><h1>Correção de atividades</h1><p>Leia o código, escreva uma orientação e marque o resultado.</p></div><Link href="/professor">← Voltar ao painel</Link></header><div className="review-filters"><select value={className} onChange={e=>setClassName(e.target.value)}>{classes.map(x=><option key={x}>{x}</option>)}</select><select value={status} onChange={e=>setStatus(e.target.value)}><option value="entregue">Aguardando correção</option><option value="refazer">Para refazer</option><option value="corrigida">Corrigidas</option><option value="Todos">Todas</option></select><button onClick={load}>Atualizar</button></div>{message&&<p className="form-success">{message}</p>}<section className="review-list">{items.map(item=><ReviewCard key={item.studentId+item.lessonSlug} item={item} onSave={save}/>) }{items.length===0&&<p className="empty-state">Nenhuma atividade neste filtro.</p>}</section></main>
}
function ReviewCard({item,onSave}:{item:Review;onSave:(item:Review,status:string,feedback:string)=>void}){const [feedback,setFeedback]=useState(item.teacherFeedback),[status,setStatus]=useState(item.reviewStatus);const title=[...lessons,...logicLessons].find(x=>x.slug===item.lessonSlug)?.title||item.lessonSlug;return <article className="review-card"><div className="review-meta"><div><b>{item.name}</b><span>{item.className}</span></div><span className={"review-status "+status}>{status}</span></div><h2>{title}</h2><pre>{item.answer}</pre><label>Comentário para o aluno<textarea value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Explique o que ficou bom e o que precisa melhorar."/></label><div className="review-actions"><select value={status} onChange={e=>setStatus(e.target.value)}><option value="entregue">Aguardando</option><option value="refazer">Pedir para refazer</option><option value="corrigida">Corrigida</option></select><button onClick={()=>onSave(item,status,feedback)}>Salvar correção</button></div></article>}